# Site settings
title: svettwer
description: Personal page with some info about me and what I do.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://svettwer.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sven Hettwer
user_title: Software Engineer
email: sven.hettwer@web.de
twitter_username: SvenHettwer
github_username:  svettwer
twitch_username:  svettwer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
