name: Release my website <3

on:
  push:
    branches: [ develop ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Commit files
      run: |
        mv ${{ github.workspace }}/_site/* ${{ github.workspace }}
        git config --local user.email "sven.hettwer@web.de"
        git config --local user.name "svettwer"
        git commit -m "New website release <3" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
